#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/110-kruemmung/1-kruemmung.tex				\
	chapters/110-kruemmung/2-flaeche.tex				\
	chapters/110-kruemmung/3-schnittkruemmung.tex			\
	chapters/110-kruemmung/4-ricci.tex				\
	chapters/110-kruemmung/5-newton.tex				\
	chapters/110-kruemmung/6-feldgleichungen.tex			\
	chapters/110-kruemmung/7-schwarzeloecher.tex			\
	chapters/110-kruemmung/8-friedmann.tex				\
	chapters/110-kruemmung/chapter.tex
