%
% randpoints.m -- erzeuge Gitter von Punkten mit zufälligen Abweichungen
%
% (c) 2025 Prof Dr Andreas Müller
%
global h;
h = 2.0;
global r;
r = 0.2;

rand("seed", 4711);

function retval = f()
	global r;
	retval = r * (rand(1) - 1);
end

function punkt(fd, name, x, y)
	global h;
	fprintf(fd, "\\coordinate (%s) at (%.4f,%.4f);\n", name,
		(x + f()) * h, (y + f()) * h);
end

fd = fopen("randpoints.tex", "w");

fprintf(fd, "%%\n");
fprintf(fd, "%% randpoints.tex -- generated by randpoints.m - do not modify!\n");
fprintf(fd, "%%\n");
fprintf(fd, "%% (c) 2025 Prof Dr Andreas Müller\n");
fprintf(fd, "%%\n");

punkt(fd, "A0", -2, 0);
punkt(fd, "A1", -1, 0);
punkt(fd, "A2",  0, 0);
punkt(fd, "A3",  1, 0);
punkt(fd, "A4",  2, 0);

punkt(fd, "B0", -1.5, sqrt(3)/2);
punkt(fd, "B1", -0.5, sqrt(3)/2);
punkt(fd, "B2",  0.5, sqrt(3)/2);
punkt(fd, "B3",  1.5, sqrt(3)/2);

punkt(fd, "B4", -1, sqrt(3));
punkt(fd, "B5",  0, sqrt(3));
punkt(fd, "B6",  1, sqrt(3));

punkt(fd, "C0", -1.5, -sqrt(3)/2);
punkt(fd, "C1", -0.5, -sqrt(3)/2);
punkt(fd, "C2",  0.5, -sqrt(3)/2);
punkt(fd, "C3",  1.5, -sqrt(3)/2);

punkt(fd, "C4", -1, -sqrt(3));
punkt(fd, "C5",  0, -sqrt(3));
punkt(fd, "C6",  1, -sqrt(3));

fclose(fd);
