#
# Makefile - TikZ-Images
#
# (c) 2025 Prof Dr Andreas Müller
#
all:	stationaer.pdf							\
	speedup500.pdf							\
	speedup5000.pdf							\
	speedup10000.pdf

stationaer.pdf:	stationaer.tex
	pdflatex stationaer.tex

speedup500.pdf:	speedup500.tex
	pdflatex speedup500.tex

speedup5000.pdf:	speedup5000.tex
	pdflatex speedup5000.tex

speedup10000.pdf:	speedup10000.tex
	pdflatex speedup10000.tex

