#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/100-zusammenhang/1-parallel.tex			\
	chapters/100-zusammenhang/2-geodaeten.tex			\
	chapters/100-zusammenhang/3-divergenz.tex			\
	chapters/100-zusammenhang/4-zusammenhang.tex			\
	chapters/100-zusammenhang/chapter.tex
