#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/120-topologie/1-simplex.tex				\
	chapters/120-topologie/2-morse.tex				\
	chapters/120-topologie/3-derham.tex				\
	chapters/120-topologie/chapter.tex
